import React from 'react';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, expect, it, vi } from 'vitest';
import Page from './page';
import { apiListModerationCases, apiGetModerationCase, apiResolveEscalatedCancellation } from '@/api/admin.api';
import { safetyCase } from '@/test/fixtures/moderation-cases';
const mocks = vi.hoisted(() => ({ query: '', success: vi.fn() }));
vi.mock('next/navigation', () => ({ useRouter: () => ({ replace: vi.fn(), push: vi.fn() }), useSearchParams: () => new URLSearchParams(mocks.query) }));
vi.mock('next/link', () => ({ default: ({ children, href, ...props }: React.ComponentProps<'a'>) => <a href={href} {...props}>{children}</a> }));
vi.mock('@/components/ui/Toast', () => ({ useToast: () => ({ success: mocks.success, error: vi.fn() }) }));
vi.mock('@/lib/socket', () => ({ getSocket: () => null }));
vi.mock('@/components/admin/cases/BookingOperations', () => ({ default: () => <p>Operational tools</p> }));
vi.mock('@/api/admin.api', () => ({ apiListModerationCases: vi.fn(), apiGetModerationCase: vi.fn(), apiResolveReport: vi.fn(), apiResolveCompletionEscalation: vi.fn(), apiResolveEscalatedCancellation: vi.fn() }));
const response = { data: [safetyCase], summary: { active: 1, underReview: 1, history: 3, concerns: { INAPPROPRIATE_BEHAVIOR: 1 } }, pagination: { total: 1, totalPages: 1 } };
beforeEach(() => { vi.clearAllMocks(); mocks.query = ''; vi.mocked(apiListModerationCases).mockResolvedValue(response); });
it('starts with the active queue and delegates concern, payment and status filters to the server', async () => {
  render(<Page />); await screen.findByRole('button', { name: 'Open case' });
  expect(apiListModerationCases).toHaveBeenCalledWith(expect.objectContaining({ view: 'active', sort: 'attention', page: 1, limit: 12 }));
  expect(screen.getByLabelText('Case status')).toBeVisible();
  expect(screen.getByLabelText('Case type')).toBeVisible();
  expect(screen.getByLabelText('Payment method')).toBeVisible();
  fireEvent.click(screen.getByRole('button', { name: 'More filters' }));
  fireEvent.change(screen.getByLabelText('Concern'), { target: { value: 'SCAM_OR_FRAUD' } });
  fireEvent.change(screen.getByLabelText('Payment method'), { target: { value: 'GCash' } });
  fireEvent.change(screen.getByLabelText('Case status'), { target: { value: 'UNDER_REVIEW' } });
  await waitFor(() => expect(apiListModerationCases).toHaveBeenLastCalledWith(expect.objectContaining({ concern: 'SCAM_OR_FRAUD', payment: 'GCash', status: 'UNDER_REVIEW', page: 1 })));
});
it('searches the full queue and offers closed-case history', async () => {
  render(<Page />); await screen.findByRole('button', { name: 'Open case' });
  fireEvent.change(screen.getByRole('searchbox'), { target: { value: 'Mara' } });
  await waitFor(() => expect(apiListModerationCases).toHaveBeenLastCalledWith(expect.objectContaining({ search: 'Mara' })));
  fireEvent.click(screen.getByRole('button', { name: /Case history/ }));
  await waitFor(() => expect(apiListModerationCases).toHaveBeenLastCalledWith(expect.objectContaining({ view: 'history' })));
  expect(screen.getByLabelText('Sort cases')).toHaveValue('newest');
  expect(screen.queryByRole('option', { name: /Pending/ })).not.toBeInTheDocument();
  expect(screen.getByRole('option', { name: 'Recently closed first' })).toBeInTheDocument();
});
it('removes individual filters and resets incompatible status and sorting when switching views', async () => {
  render(<Page />); await screen.findByRole('button', { name: 'Open case' });
  fireEvent.change(screen.getByLabelText('Case status'), { target: { value: 'UNDER_REVIEW' } });
  fireEvent.change(screen.getByLabelText('Payment method'), { target: { value: 'GCash' } });
  fireEvent.click(screen.getByRole('button', { name: 'Remove Payment: GCash' }));
  await waitFor(() => expect(apiListModerationCases).toHaveBeenLastCalledWith(expect.objectContaining({ status: 'UNDER_REVIEW', payment: undefined })));
  fireEvent.click(screen.getByRole('button', { name: /Case history/ }));
  await waitFor(() => expect(apiListModerationCases).toHaveBeenLastCalledWith(expect.objectContaining({ view: 'history', status: undefined, sort: 'newest' })));
  fireEvent.change(screen.getByLabelText('Case status'), { target: { value: 'RESOLVED' } });
  fireEvent.click(screen.getByRole('button', { name: 'Clear filters' }));
  expect(screen.getByLabelText('Sort cases')).toHaveValue('newest');
  fireEvent.click(screen.getByRole('button', { name: /Needs attention/ }));
  expect(screen.getByLabelText('Sort cases')).toHaveValue('attention');
});

it('reads back a closed cancellation before showing success and does not wait on the list refresh', async () => {
  mocks.query = '?case=report:qa-safety-case';
  const cancellation = { ...safetyCase, type: 'CANCELLATION_ESCALATION', concern: 'CANCELLATION_REVIEW', cancellation: { id: 'cancel-1', reason: 'Schedule changed', status: 'UNDER_REVIEW' }, allowedOutcomes: ['approve_cancellation', 'deny_cancellation'] };
  const closed = { ...cancellation, status: 'RESOLVED', allowedOutcomes: [], resolvedAt: '2026-10-04T08:03:00Z', cancellation: { ...cancellation.cancellation, status: 'RESOLVED', resolutionOutcome: 'APPROVED' }, decisionExplanation: 'Cancellation approved.', booking: { ...cancellation.booking, status: 'CANCELED', paymentMethod: 'On-site Cash', paymentStatus: 'UNPAID' } };
  vi.mocked(apiGetModerationCase).mockResolvedValueOnce({ data: cancellation }).mockResolvedValue({ data: closed });
  vi.mocked(apiResolveEscalatedCancellation).mockResolvedValue({ success: true });
  render(<Page />); await screen.findByRole('radio', { name: /Approve cancellation/ });
  fireEvent.click(screen.getByRole('radio', { name: /Approve cancellation/ }));
  fireEvent.change(screen.getByLabelText(/Who was at fault/), { target: { value: 'none' } });
  fireEvent.change(screen.getByLabelText(/Decision explanation/), { target: { value: 'Cancellation approved.' } });
  fireEvent.click(screen.getByRole('button', { name: 'Review decision' }));
  fireEvent.click(screen.getByRole('checkbox', { name: /I reviewed/ }));
  vi.mocked(apiListModerationCases).mockImplementation(() => new Promise(() => {}));
  fireEvent.click(screen.getByRole('button', { name: 'Confirm decision' }));
  await screen.findByRole('heading', { name: 'Recorded decision' });
  expect(apiResolveEscalatedCancellation).toHaveBeenCalledWith('cancel-1', true, 'Cancellation approved.', 'none');
  expect(screen.getByText('Resolved — Cancellation approved')).toBeInTheDocument();
  expect(screen.queryByRole('button', { name: 'Saving decision…' })).not.toBeInTheDocument();
  await waitFor(() => expect(screen.getByRole('button', { name: /Back to cases/ })).toBeEnabled());
  expect(mocks.success).toHaveBeenCalledWith('Case closed', expect.any(String));
});

it('does not claim success when a submitted cancellation still reads back under review', async () => {
  mocks.query = '?case=report:qa-safety-case';
  const cancellation = { ...safetyCase, type: 'CANCELLATION_ESCALATION', concern: 'CANCELLATION_REVIEW', cancellation: { id: 'cancel-1', reason: 'Schedule changed', status: 'UNDER_REVIEW' }, allowedOutcomes: ['approve_cancellation', 'deny_cancellation'] };
  vi.mocked(apiGetModerationCase).mockResolvedValue({ data: cancellation });
  vi.mocked(apiResolveEscalatedCancellation).mockResolvedValue({ success: true });
  render(<Page />); await screen.findByRole('radio', { name: /Approve cancellation/ });
  fireEvent.click(screen.getByRole('radio', { name: /Approve cancellation/ }));
  fireEvent.change(screen.getByLabelText(/Who was at fault/), { target: { value: 'provider' } });
  fireEvent.change(screen.getByLabelText(/Decision explanation/), { target: { value: 'Cancellation approved.' } });
  fireEvent.click(screen.getByRole('button', { name: 'Review decision' }));
  fireEvent.click(screen.getByRole('checkbox', { name: /I reviewed/ }));
  fireEvent.click(screen.getByRole('button', { name: 'Confirm decision' }));
  expect(await screen.findByRole('alert')).toHaveTextContent('case is still open');
  expect(apiResolveEscalatedCancellation).toHaveBeenCalledWith('cancel-1', true, 'Cancellation approved.', 'provider');
  expect(mocks.success).not.toHaveBeenCalled();
  expect(screen.getByRole('button', { name: 'Confirm decision' })).toBeEnabled();
});
it('uses an error state with retry instead of pretending the queue is empty', async () => {
  vi.mocked(apiListModerationCases).mockRejectedValue(new Error('offline'));
  render(<Page />);
  expect(await screen.findByRole('button', { name: 'Retry loading' })).toBeInTheDocument();
  expect(screen.queryByText('No cases need attention')).not.toBeInTheDocument();
});
it('distinguishes public content from booking cases with links to both workflows', async () => {
  render(<Page />); await screen.findByRole('button', { name: 'Open case' });
  const navigation = screen.getByRole('navigation', { name: 'Report workflows' });
  expect(navigation).toHaveTextContent('Listings and public requests');
  expect(navigation).toHaveTextContent('Bookings, services and payments');
  expect(screen.getByRole('link', { name: /Content Reports & Appeals/ })).toHaveAttribute('href', '/admin/content-cases');
  expect(screen.getByRole('link', { name: /Disputes & Reports/ })).toHaveAttribute('aria-current', 'page');
});
it('switches and toggles quick filters without keeping an incompatible escalation type', async () => {
  vi.mocked(apiListModerationCases).mockResolvedValue({ ...response, summary: { ...response.summary, concerns: { INAPPROPRIATE_BEHAVIOR: 1, COMPLETION_REVIEW: 1 } } });
  render(<Page />); await screen.findByRole('button', { name: 'Open case' });
  const completion = screen.getByRole('button', { name: 'Completion review 1' });
  const safety = screen.getByRole('button', { name: 'Inappropriate behavior 1' });
  fireEvent.click(completion);
  await waitFor(() => expect(apiListModerationCases).toHaveBeenLastCalledWith(expect.objectContaining({ type: 'COMPLETION_ESCALATION', concern: undefined })));
  expect(completion).toHaveAttribute('aria-pressed', 'true');
  fireEvent.click(safety);
  await waitFor(() => expect(apiListModerationCases).toHaveBeenLastCalledWith(expect.objectContaining({ type: undefined, concern: 'INAPPROPRIATE_BEHAVIOR' })));
  expect(completion).toHaveAttribute('aria-pressed', 'false');
  expect(safety).toHaveAttribute('aria-pressed', 'true');
  fireEvent.click(safety);
  await waitFor(() => expect(apiListModerationCases).toHaveBeenLastCalledWith(expect.objectContaining({ type: undefined, concern: undefined })));
  fireEvent.click(completion); fireEvent.click(completion);
  await waitFor(() => expect(apiListModerationCases).toHaveBeenLastCalledWith(expect.objectContaining({ type: undefined, concern: undefined })));
});
